# Generated by Django 4.0 on 2021-12-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
