# Generated by Django 4.0 on 2021-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
